### ISSUE TITLE
when trying to bookmark a codespace, on the tutorial it says "keep codespace" but when actually trying to do it the options now are "auto-delete codespace"

### ISSUE THREAD

**Issue by bibimbop123** [appdev-lessons/codespaces-setup#1]
<img width="1533" alt="Screenshot 2023-12-24 at 10 41 24 AM" src="https://github.com/appdev-lessons/codespaces-setup/assets/122857543/ae1eaed6-6efa-4354-9ddf-6c030c13307d">
<img width="1705" alt="Screenshot 2023-12-24 at 10 41 52 AM" src="https://github.com/appdev-lessons/codespaces-setup/assets/122857543/b8a23d8f-1101-4437-b1a7-8c6bf3ae4214">

**Comment by bpurinton** [comment]
Ah, nice catch. Always hard to keep our screenshots up-to-date with the constantly changing UI of GitHub. I'll update this section of the lesson.
